#include <cstring>
#include <iostream>
#include <cstdint>
#include <unordered_map>
#include <memory>
#include <vector>
#include <fstream>
#include <string>
#include <leveldb/db.h>
#include <filesystem>
#include <direct.h>
